name: Deploy to Cloudflare Pages

on:
  repository_dispatch:
    types: [on-demand-release]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build & Deploy
    steps:
      - name: Checkout to private repo
        uses: actions/checkout@v6
        with:
          repository: seiry/astro-blog
          token: ${{ secrets.GH_TOKEN_FOR_CHECKOUT }}

      - name: Cache dependencies & Astro build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.cache/yarn
            ~/.yarn/cache
            ~/.pnpm-store
            ~/.bun/install/cache
            ~/.cache/bun
            .astro
            node_modules/.cache
          key: ${{ runner.os }}-astro-${{ hashFiles('**/pnpm-lock.yaml', '**/package-lock.json', '**/npm-shrinkwrap.json', '**/yarn.lock', '**/bun.lockb', '**/bun.lock', '**/deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-astro-

      - name: Install, build, and upload your site output
        uses: withastro/action@v5
        # with:
          # package-manager: bun
          
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }} 
